var express = require('express');
var router = express.Router();

const glossaryList = [
  { ID: '1', Term: "DveOps", Description: "It's an acronym for development and operations at first, It's an IT operaing model that improve product development efficiency", Reference: 'Mason, G. (2022) ‘Remove the Walls of Confusion: Rethink DevOps to Unlock its Full Value’, Linkedin, 1 February. Available at: https://www.linkedin.com/pulse/remove-walls-confusion-rethink-devops-unlock-its-full-glenn-mason/ (Accessed: 22 July 2023).' },
  { ID: '2', Term: "Wall of Confusion", Description: "When passing to the next group, that group always considers their deliverables arer completed in work flow.", Reference: 'Kawaguchi, S. (2022) The Wall of Confusion, Medium. Available at: https://levelup.gitconnected.com/the-wall-of-confusion-623057a4dd26 (Accessed: 22 July 2023).' },
  { ID: '3', Term: "Shift Left", Description: "In early software engineering, the next step will not start until the previous step 100% complete. Shift left means the entire development process will start writing earlier and deliver faster.", Reference: 'Kawaguchi, S. (2022) The Wall of Confusion, Medium. Available at: https://levelup.gitconnected.com/the-wall-of-confusion-623057a4dd26 (Accessed: 22 July 2023).' },
  { ID: '4', Term: "CI", Description: "CI is continuous integration which means integrating newly developed code with the rest of the software.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '5', Term: "Kanban cards", Description: "It's also a structure of alige development approach which needs to communicate continuously and visualize the work in progress, which greatly improves work efficiency.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '6', Term: "CD", Description: "CD is continuous delivery which means the team will release their products in a high frequency and can ensure its high quality", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '7', Term: "Agile", Description: "It's one of the development approach and it's an iterative approach. It amis to continuously deliever working projects through apid iterations.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '8', Term: "Scrum", Description: "It's agile project management framework, it is an incremental, iterative development process that help teams cooperate better.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '9', Term: "KanPlan", Description: "It's also one of agile development approach but it's a mixture one. It mixes featuers of another two agile development approaches: KanBan and Scrum. It's best choice for teams which can't work in sprints but want to deal with backlog.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '10', Term: "CX", Description: "CX is customer service which can reflect the interaction between the enterprise and the customer at each node of the customer purchase journey. It's key in DevOps.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '11', Term: "MVP", Description: "MVP means Minimum Viable Product. That's the first iteration of product which not meet all the requirements.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '12', Term: "DoD", Description: "DoD(definition of done) means the product is completely done and meet all the requirements.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '13', Term: "SLAs", Description: "SLA is service-level aggreements which is the level of service that the service provider promises to the customer.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '14', Term: "KPIs", Description: "KPI is key performance indicator. It's usually used to evaluate performance, report progress and help tp achieve business goals.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '15', Term: "MTTR", Description: "MTTR is mean time of recovery which is one of KPIs, it means how fast the failure can be detected and sloved.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '16', Term: "DevOps cycle", Description: "DevOps cycle is an architecture model and been shown as an infinite loop that contains important steps and components within the DevOps.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '17', Term: "Demand management", Description: "Demand management can be described as a process from enterprise coming up with ideas to realizing business value.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '18', Term: "Portfolio management", Description: "Portfolio management is a consistency assessment on market demands and related activities.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '19', Term: "Configuration management", Description: "Configuration management is to manage artifacts and confirm these artifacts are suitable for portfolio.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '20', Term: "IaC", Description: "IaC means Infrastructure as Code. Everything can become codes. It manages infrastructure via coding.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },

  { ID: '21', Term: "Container", Description: "It is a lightweight standalone execution environment that contains everything needed to run an application", Reference: 'Davis, A. (2021) Bootstrapping microservices with Docker, Kubernetes, and Terraform, O’Reilly Online Learning. Available at: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212/?sso_link=yes&amp;sso_link_from=Deakin (Accessed: 02 September 2023). ' },
  { ID: '22', Term: "VMs", Description: "It is a virtualization technology that allows the creation of multiple independent virtual operating system instances on a single physical computer. ", Reference: 'Davis, A. (2021) Bootstrapping microservices with Docker, Kubernetes, and Terraform, O’Reilly Online Learning. Available at: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212/?sso_link=yes&amp;sso_link_from=Deakin (Accessed: 02 September 2023). ' },
  { ID: '23', Term: "Image", Description: "It is one of the fundamental building blocks of containers. An image is a lightweight, self-contained executable package that contains everything needed to run an application", Reference: 'Davis, A. (2021) Bootstrapping microservices with Docker, Kubernetes, and Terraform, O’Reilly Online Learning. Available at: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212/?sso_link=yes&amp;sso_link_from=Deakin (Accessed: 02 September 2023). ' },
  { ID: '24', Term: "Portfolio implementation", Description: "Make changes to the portfolio in a fixed process", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).' },
  { ID: '25', Term: "Enterprise vision", Description: "It's a part of enterprise architecture which outlines the long-term goals of the enterprise.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).'},
  { ID: '26', Term: "Ongoing components", Description: "To check whether the current products have strong connection with enterprise and target customers.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).'},
  { ID: '27', Term: "Components assessment", Description: "This is an assessment of various aspects of the business case, like how much the budget is, how much this case can earn.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).' },
  { ID: '28', Term: "Budgeting", Description: "It is a financial plan which outlines the expected income and expenditures of individuals or organizations.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).'},
  { ID: '29', Term: "Prioritization and selection", Description: "During development, select tasks that are prioritized or must be completed.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).'},
  { ID: '30', Term: "RACI", Description: "RACI means responsible, accountable, consulted and informed which is a recommended way to establish communication.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September).'},

];


/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { title: 'Welcome to my SIT722 glossary', sub: 'SIT722 Glossary List', glossary: glossaryList });
});



module.exports = router;