var express = require('express');
var router = express.Router();

const glossaryList = [
  { ID: '1', Term: "DveOps", Description: "It's an acronym for development and operations at first, It's an IT operaing model that improve product development efficiency", Reference: 'Mason, G. (2022) ‘Remove the Walls of Confusion: Rethink DevOps to Unlock its Full Value’, Linkedin, 1 February. Available at: https://www.linkedin.com/pulse/remove-walls-confusion-rethink-devops-unlock-its-full-glenn-mason/ (Accessed: 22 July 2023).' },
  { ID: '2', Term: "Wall of Confusion", Description: "When passing to the next group, that group always considers their deliverables arer completed in work flow.", Reference: 'Kawaguchi, S. (2022) The Wall of Confusion, Medium. Available at: https://levelup.gitconnected.com/the-wall-of-confusion-623057a4dd26 (Accessed: 22 July 2023).' },
  { ID: '3', Term: "Shift Left", Description: "In early software engineering, the next step will not start until the previous step 100% complete. Shift left means the entire development process will start writing earlier and deliver faster.", Reference: 'Kawaguchi, S. (2022) The Wall of Confusion, Medium. Available at: https://levelup.gitconnected.com/the-wall-of-confusion-623057a4dd26 (Accessed: 22 July 2023).' },
  { ID: '4', Term: "CI", Description: "CI is continuous integration which means integrating newly developed code with the rest of the software.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '5', Term: "Kanban cards", Description: "It's also a structure of alige development approach which needs to communicate continuously and visualize the work in progress, which greatly improves work efficiency.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '6', Term: "CD", Description: "CD is continuous delivery which means the team will release their products in a high frequency and can ensure its high quality", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '7', Term: "Agile", Description: "It's one of the development approach and it's an iterative approach. It amis to continuously deliever working projects through apid iterations.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '8', Term: "Scrum", Description: "It's agile project management framework, it is an incremental, iterative development process that help teams cooperate better.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '9', Term: "KanPlan", Description: "It's also one of agile development approach but it's a mixture one. It mixes featuers of another two agile development approaches: KanBan and Scrum. It's best choice for teams which can't work in sprints but want to deal with backlog.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  { ID: '10', Term: "CX", Description: "CX is customer service which can reflect the interaction between the enterprise and the customer at each node of the customer purchase journey. It's key in DevOps.", Reference: 'Coupland, M. author. (2021) DevOps Adoption Strategies : Principles, Processes, Tools, and Trends. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4688682&site=eds-live&scope=site (Accessed: 23 July 2023).' },
  
  { ID: '11', Term: "MVP", Description: "MVP means Minimum Viable Product. That's the first iteration of product which not meet all the requirements.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '12', Term: "DoD", Description: "DoD(definition of done) means the product is completely done and meet all the requirements.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '13', Term: "SLAs", Description: "SLA is service-level aggreements which is the level of service that the service provider promises to the customer.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '14', Term: "KPIs", Description: "KPI is key performance indicator. It's usually used to evaluate performance, report progress and help tp achieve business goals.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '15', Term: "MTTR", Description: "MTTR is mean time of recovery which is one of KPIs, it means how fast the failure can be detected and sloved.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '16', Term: "DevOps cycle", Description: "DevOps cycle is an architecture model and been shown as an infinite loop that contains important steps and components within the DevOps.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '17', Term: "Demand management", Description: "Demand management can be described as a process from enterprise coming up with ideas to realizing business value.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '18', Term: "Portfolio management", Description: "Portfolio management is a consistency assessment on market demands and related activities.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '19', Term: "Configuration management", Description: "Configuration management is to manage artifacts and confirm these artifacts are suitable for portfolio.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },
  { ID: '20', Term: "IaC", Description: "IaC means Infrastructure as Code. Everything can become codes. It manages infrastructure via coding.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 6 August 2023).' },

  { ID: '21', Term: "Container", Description: "It is a lightweight standalone execution environment that contains everything needed to run an application", Reference: 'Davis, A. (2021) Bootstrapping microservices with Docker, Kubernetes, and Terraform, O’Reilly Online Learning. Available at: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212/?sso_link=yes&amp;sso_link_from=Deakin (Accessed: 02 September 2023). ' },
  { ID: '22', Term: "VMs", Description: "It is a virtualization technology that allows the creation of multiple independent virtual operating system instances on a single physical computer. ", Reference: 'Davis, A. (2021) Bootstrapping microservices with Docker, Kubernetes, and Terraform, O’Reilly Online Learning. Available at: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212/?sso_link=yes&amp;sso_link_from=Deakin (Accessed: 02 September 2023). ' },
  { ID: '23', Term: "Image", Description: "It is one of the fundamental building blocks of containers. An image is a lightweight, self-contained executable package that contains everything needed to run an application", Reference: 'Davis, A. (2021) Bootstrapping microservices with Docker, Kubernetes, and Terraform, O’Reilly Online Learning. Available at: https://learning.oreilly.com/library/view/bootstrapping-microservices-with/9781617297212/?sso_link=yes&amp;sso_link_from=Deakin (Accessed: 02 September 2023). ' },
  { ID: '24', Term: "Portfolio implementation", Description: "Make changes to the portfolio in a fixed process", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).' },
  { ID: '25', Term: "Enterprise vision", Description: "It's a part of enterprise architecture which outlines the long-term goals of the enterprise.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).'},
  { ID: '26', Term: "Ongoing components", Description: "To check whether the current products have strong connection with enterprise and target customers.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).'},
  { ID: '27', Term: "Components assessment", Description: "This is an assessment of various aspects of the business case, like how much the budget is, how much this case can earn.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).' },
  { ID: '28', Term: "Budgeting", Description: "It is a financial plan which outlines the expected income and expenditures of individuals or organizations.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).'},
  { ID: '29', Term: "Prioritization and selection", Description: "During development, select tasks that are prioritized or must be completed.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September 2023).'},
  { ID: '30', Term: "Portfolio governance and communication", Description: "RACI means responsible, accountable, consulted and informed which is a recommended way to establish communication.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 2 September).'},
  
  { ID: '31', Term: "Portfolio reporting and review", Description: "It's a related prrocess in portfolio management which should evaluate if the portfolio aligns with the company's strategic objectives.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '32', Term: "Benefits realization", Description: "It's a related process in portfolio management. In this step, understand the true worth of the portfolio and its advantages for the company and its operations", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '33', Term: "Automation", Description: "It refers to the practice of using software to automatically manage and streamline the process of designing, testing, deploying, and monitoring applications", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '34', Term: "Version control", Description: "Version control is essential to ensure uniformity in all configuration elements. A build creates a package with a specific version, which can be fetched from the storage location.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '35', Term: "Configuration items", Description: "It's an IT library for IT service management. Configuration items are resources that must be overseen to provide an IT service effectively.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '36', Term: "Continuous testing", Description: "Continuous testing is employed to detect and anticipate problems in code modifications, execute various tests, and eventually deploy validated automated versions.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '37', Term: "Community driven", Description: "Vast groups consistently enhance the software, and businesses can gain advantages from these improvements.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '38', Term: "Cost-effective", Description: "While open-source software usually requires licensing, the overall expenses often make it a cost-effective option.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '39', Term: "No risk of lock-in", Description: "They wish to avoid being entirely bound to a single software vendor or that vendor's environment. Which is more important for organizations.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '40', Term: "Standardization", Description: "Standardization contains Portfolio management, version control and configuration items.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
 
  { ID: '41', Term: "ITIL", Description: "ITTL means IT Infrastructure Library which is an IT library for IT service management.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '42', Term: "UUID", Description: "UUID means unique identifier. UUIDs are used in various software development scenarios.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '43', Term: "CMDB", Description: "CMDB means Configuration Management Database. It is a centralized repository that contains information about all the significant entities in an IT environmen", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '44', Term: "IP", Description: "IP means Internet Protocol.  It is a set of rules governing how data is sent and received over the internet.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '45', Term: "Code pipelines", Description: "Code pipelines are automated workflows that enable continuous integration and continuous delivery (CI/CD) of software applications.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '46', Term: "Integration tests", Description: "The compiled package undergoes testing to confirm it operates flawlessly, and results are documented in test summaries.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '47', Term: "Unit tests", Description: "Unit tests verify that the compiled software package operates without problems.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '48', Term: "Static code analysis", Description: " It's approach that can be used to increase quality and get feedback to ensure no issues orrur.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '49', Term: "Source code quality analysis", Description: "The code is reviewed to ensure it adheres to security and compliance standards. This quality assessment also includes an examination of the software utilized.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'},
  { ID: '50', Term: "Build notification", Description: "It's the last step before deployment. It notices that the code and packages have passed all tests without errors.", Reference: 'Mulder, J. author. (2021) Enterprise DevOps for Architects. 1st edition. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4727315&site=eds-live&scope=site (Accessed: 15 September).'}

];


/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { title: 'Welcome to my SIT722 glossary', sub: 'SIT722 Glossary List', glossary: glossaryList });
});



module.exports = router;